[package]
name = "pingap-core"
version = "0.10.4"
edition = "2021"
authors = ["Tree Xie <tree.xie@outlook.com>"]
license = "Apache-2.0"
homepage = "https://github.com/vicanso/pingap"
repository = "https://github.com/vicanso/pingap"
keywords = ["pingap", "core"]


[dependencies]
ahash = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
pingora = { workspace = true }
itoa = { workspace = true }
snafu = { workspace = true }
async-trait = { workspace = true }
once_cell = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }
TinyUFO = "0.4.0"
hostname = "0.4.0"
pingora-limits = "0.4.0"
opentelemetry = { version = "0.28.0", default-features = false, features = [
    "trace",
], optional = true }


[features]
full = ["opentelemetry"]

[dev-dependencies]
pretty_assertions = "1.4.0"
tempfile = "3.16.0"
tokio-test = "0.4.4"
