[package]
name = "pingap-cache"
version = "0.9.10"
edition = "2021"
authors = ["Tree Xie <tree.xie@outlook.com>"]
license = "Apache-2.0"
homepage = "https://github.com/vicanso/pingap"
repository = "https://github.com/vicanso/pingap"
keywords = ["pingap", "cache"]


[lib]
name = "pingap_cache"
path = "src/lib.rs"

[features]
full = ["prometheus"]

[dependencies]
bytesize = { workspace = true }
memory-stats = { workspace = true }
once_cell = { workspace = true }
snafu = { workspace = true }
TinyUFO = { workspace = true }
scopeguard = { workspace = true }
pingora = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
http = { workspace = true }

prometheus = { version = "0.13.4", default-features = false, optional = true }
pingap-config = { path = "../pingap-config" }
pingap-util = { path = "../pingap-util" }
pingap-core = { path = "../pingap-core" }

[dev-dependencies]
pretty_assertions = "1.4.0"
tempfile = "3.16.0"
tokio-test = "0.4.4"
