[package]
name = "pingap-cache"
version = "0.10.2"
edition = "2021"
authors = ["Tree Xie <tree.xie@outlook.com>"]
license = "Apache-2.0"
homepage = "https://github.com/vicanso/pingap"
repository = "https://github.com/vicanso/pingap"
keywords = ["pingap", "cache"]


[lib]
name = "pingap_cache"
path = "src/lib.rs"

[features]
full = ["prometheus"]

[dependencies]
substring = { workspace = true }
dirs = { workspace = true }
path-absolutize = { workspace = true }
bytesize = { workspace = true }
memory-stats = { workspace = true }
once_cell = { workspace = true }
snafu = { workspace = true }
scopeguard = { workspace = true }
pingora = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
http = { workspace = true }
prometheus = { version = "0.13.4", default-features = false, optional = true }
pingap-core = { version = "0.10.2", path = "../pingap-core" }

[dev-dependencies]
pretty_assertions = "1.4.0"
tempfile = "3.16.0"
tokio-test = "0.4.4"
