[package]
name = "pingap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.78"
bytes = "1.5.0"
bytesize = "1.3.0"
chrono = "0.4.35"
clap = { version = "4.5.3", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.11.3"
futures-util = "0.3.30"
glob = "0.3.1"
http = "1.1.0"
humantime = "2.1.0"
humantime-serde = "1.1.1"
log = "0.4.21"
num_cpus = "1.16.0"
path-absolutize = "3.1.1"
pingora = { version = "0.1.0", features = ["lb"] }
regex = "1.10.3"
serde = "1.0.197"
snafu = "0.8.2"
substring = "1.4.5"
toml = "0.8.12"
url = "2.5.0"

[profile.release]
codegen-units = 1
lto = true
