[package]
name = "pingap"
version = "0.1.25"
authors = ["Tree Xie <tree.xie@outlook.com>"]
edition = "2021"
categories = ["network-programming", "web-programming::http-server"]
keywords = ["proxy", "http", "gateway"]
description = "A reverse proxy like nginx"
license = "Apache-2.0"
homepage = "https://github.com/vicanso/pingap"
repository = "https://github.com/vicanso/pingap"
exclude = ["asset/*", "test/*", "Cargo.lock", "web/*", "dist/*", ".github/*"]
readme = "./README.md"
rust-version = "1.74"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
base64 = "0.22.0"
bytes = "1.6.0"
bytesize = "1.3.0"
chrono = "0.4.37"
clap = { version = "4.5.4", features = ["derive"] }
crc32fast = "1.4.0"
dirs = "5.0.1"
env_logger = "0.11.3"
futures-util = "0.3.30"
glob = "0.3.1"
hex = "0.4.3"
hostname = "0.3.1"
http = "1.1.0"
humantime = "2.1.0"
humantime-serde = "1.1.1"
ipnet = "2.9.0"
log = "0.4.21"
memory-stats = { version = "1.1.0", features = ["always_use_statm"] }
mime_guess = "2.0.4"
nanoid = "0.4.0"
nix = { version = "0.28.0", features = ["signal"] }
num_cpus = "1.16.0"
once_cell = "1.19.0"
path-absolutize = "3.1.1"
pingora = { version = "0.1.1", default-features = false, features = [
    "lb",
    "openssl",
    "cache",
] }
pingora-limits = "0.1.1"
regex = "1.10.4"
reqwest = { version = "0.11.27", features = ["json"] }
rust-embed = { version = "8.3.0", features = ["mime-guess", "compression"] }
serde = "1.0.197"
serde_json = "1.0.115"
serde_repr = "0.1.19"
snafu = "0.8.2"
substring = "1.4.5"
tempfile = "3.10.1"
tokio = { version = "1.37.0", features = ["fs"] }
toml = "0.8.12"
url = "2.5.0"
urlencoding = "2.1.3"
uuid = { version = "1.8.0", features = ["v4", "fast-rng"] }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
pretty_assertions = "1.4.0"
tokio-test = "0.4.4"

[profile.release]
codegen-units = 1
lto = true
strip = "debuginfo"


[[bench]]
name = "bench"
harness = false
