[package]
name = "pingap"
version = "0.5.5"
authors = ["Tree Xie <tree.xie@outlook.com>"]
edition = "2021"
categories = ["network-programming", "web-programming::http-server"]
keywords = ["proxy", "http", "gateway"]
description = "A reverse proxy like nginx"
license = "Apache-2.0"
homepage = "https://github.com/vicanso/pingap"
repository = "https://github.com/vicanso/pingap"
exclude = ["asset/*", "test/*", "Cargo.lock", "web/*", ".github/*", "docs/*"]
readme = "./README.md"
rust-version = "1.74"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
base64 = "0.22.0"
bytes = "1.6.0"
bytesize = "1.3.0"
chrono = { version = "0.4.38", default-features = false, features = [
    "std",
    "clock",
] }
clap = { version = "4.5.4", features = ["derive"] }
cookie = "0.18.1"
crc32fast = "1.4.2"
crossbeam-channel = "0.5.13"
dhat = { version = "0.3.3", optional = true }
diff = "0.1.13"
dirs = "5.0.1"
env_logger = "0.11.3"
etcd-client = "0.12.4"
futures-util = "0.3.30"
glob = "0.3.1"
hex = "0.4.3"
hostname = "0.4.0"
http = "1.1.0"
humantime = "2.1.0"
humantime-serde = "1.1.1"
instant-acme = "0.4.3"
ipnet = "2.9.0"
libc = "0.2.154"
local-ip-address = "0.6.1"
log = "0.4.21"
lru = "0.12.3"
memory-stats = { version = "1.1.0", features = ["always_use_statm"] }
mime_guess = "2.0.4"
nanoid = "0.4.0"
nix = { version = "0.28.0", features = ["signal"] }
num_cpus = "1.16.0"
once_cell = "1.19.0"
path-absolutize = "3.1.1"
pingora = { version = "0.2.0", default-features = false, features = [
    "lb",
    "openssl",
    "cache",
] }
pingora-limits = "0.2.0"
pyroscope = { version = "0.5.7", optional = true }
pyroscope_pprofrs = { version = "0.2.7", optional = true }
rcgen = "0.12.1"
regex = "1.10.4"
reqwest = { version = "0.11.27", features = ["json"] }
rust-embed = { version = "8.4.0", features = ["mime-guess", "compression"] }
serde = "1.0.202"
serde_json = "1.0.116"
sha2 = "0.10.8"
snafu = "0.8.2"
strum = { version = "0.26.2", features = ["derive"] }
substring = "1.4.5"
tempfile = "3.10.1"
tokio = { version = "1.37.0", features = ["fs"] }
toml = "0.8.13"
url = "2.5.0"
urlencoding = "2.1.3"
uuid = { version = "1.8.0", features = ["v7", "fast-rng"] }
x509-parser = "0.16.0"

[features]
pyro = ["pyroscope", "pyroscope_pprofrs"]
perf = ["pyro", "dhat"]


[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
pretty_assertions = "1.4.0"
tokio-test = "0.4.4"

[profile.release]
codegen-units = 1
lto = true
strip = "debuginfo"

[profile.release-perf]
inherits = "release"
debug = 1
strip = "none"


[[bench]]
name = "bench"
harness = false
