[basic]
log_level = "INFO"
name = "pingap"
pid_file = "/run/pingap.pid"

[locations.testLocation]
path = "/"
upstream = "testUpstream"

[servers.testServer]
access_log = "combined"
addr = "127.0.0.1:6118"
locations = ["testLocation"]

[upstreams.testUpstream]
addrs = ["127.0.0.1:5000"]
