[basic]
error_template = ""
pid_file = "/tmp/pingap.pid"
upgrade_sock = "/tmp/pingap_upgrade.sock"
threads = 1
work_stealing = true
grace_period = "3m"
graceful_shutdown_timeout = "10s"
log_level = "info"

[upstreams.charts]
addrs = ["127.0.0.1:5000"]
algo = "hash:cookie"
health_check = "http://charts/ping?connection_timeout=3s&pingap"
connection_timeout = "10s"
total_connection_timeout = "30s"
read_timeout = "10s"
idle_timeout = "2m"
write_timeout = "10s"

[upstreams.diving]
addrs = ["127.0.0.1:5001"]


[locations.lo]
upstream = "charts"
path = "/"
host = ""
proxy_set_headers = ["name:value"]
proxy_add_headers = ["name:value"]
rewrite = ""
plugins = ["pingap:requestId", "pingap:stats"]

[servers.test]
addr = "0.0.0.0:6188"
access_log = "tiny"
locations = ["lo"]

[plugins.stats]
value = "/stats"
category = "stats"
