[basic]
cache_directory = "~/tmp/cache"
log_level = "INFO"

[locations.charts]
enable_reverse_proxy_headers = true
path = "/"
plugins = ["pingap:acceptEncodingAdjustment", "chartsCache"]
upstream = "charts"

[plugins.chartsCache]
category = "cache"
headers = ["Accept-Encoding"]
max_ttl = "1h"
namespace = "charts"
step = "request"

[servers.charts]
addr = "127.0.0.1:3000"
locations = ["charts"]

[upstreams.charts]
addrs = ["127.0.0.1:5000", "127.0.0.1:5001"]
health_check = "http://charts/ping"
