[basic]
cache_directory = "~/tmp/cache"
log_level = "INFO"

[locations.charts]
enable_reverse_proxy_headers = true
host = "charts.npmtrend.com,npmtrend.com"
path = "/"
plugins = ["pingap:acceptEncodingAdjustment", "chartsCache"]
upstream = "charts"

[locations.imageOptimize]
enable_reverse_proxy_headers = true
path = "/"
upstream = "imageOptimize"

[plugins.chartsCache]
category = "cache"
headers = ["Accept-Encoding"]
max_ttl = "1h"
namespace = "charts"

[servers.tree]
addr = "127.0.0.1:3000"
locations = ["charts", "imageOptimize"]

[upstreams.charts]
addrs = ["127.0.0.1:5000", "127.0.0.1:5001"]
health_check = "http://charts/ping"

[upstreams.imageOptimize]
addrs = ["127.0.0.1:6001"]
