[locations.staticServe]
plugins = [
    "pingap:acceptEncodingAdjustment",
    "pingap:compression",
    "staticServe",
]

[plugins.staticServe]
category = "directory"
path = "~/github/pingap/dist"

[servers.staticServe]
addr = "127.0.0.1:3000"
locations = ["staticServe"]
