[basic]

[upstreams.backend]
addrs = ["127.0.0.1:6200"]

[locations.bench]
plugins = ["pingap:ping"]

[locations.pingap-nginx]
upstream = "backend"

[servers.bench]
addr = "127.0.0.1:6100"
locations = ["bench"]
threads = 1

[servers.pingap-nginx]
addr = "127.0.0.1:6101"
locations = ["pingap-nginx"]

[plugins]

[certificates]

[storages]
