[package]
name = "pingap-acme"
version = "0.10.7"
edition = "2021"
authors = ["Tree Xie <tree.xie@outlook.com>"]
license = "Apache-2.0"
homepage = "https://github.com/vicanso/pingap"
repository = "https://github.com/vicanso/pingap"
keywords = ["pingap", "acme"]


[lib]
name = "pingap_acme"
path = "src/lib.rs"

[dependencies]
instant-acme = "0.7.2"
snafu = { workspace = true }
pingora = { workspace = true }
substring = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
pingap-certificate = { version = "0.10.7", path = "../pingap-certificate" }
pingap-config = { version = "0.10.7", path = "../pingap-config" }
pingap-core = { version = "0.10.7", path = "../pingap-core" }


[dev-dependencies]
pretty_assertions = "1.4.0"
tempfile = "3.16.0"
tokio-test = "0.4.4"
