name: "publish"
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
    # branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: build-web
        run: make build-web
      - name: release
        uses: addnab/docker-run-action@v3
        with:
          image: messense/rust-musl-cross:x86_64-musl
          options: -v ${{ github.workspace }}:/home/rust/src
          run: |
            make release
            mv target/x86_64-unknown-linux-musl/release/pingap ./pingap-linux-x86
      - name: Upload Assets
        run: |
          ./.github/workflows/upload_asset.sh ./pingap-linux-x86 $GITHUB_TOKEN

  linux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: build-web
        run: make build-web
      - name: release
        uses: addnab/docker-run-action@v3
        with:
          image: messense/rust-musl-cross:aarch64-musl
          options: -v ${{ github.workspace }}:/home/rust/src
          run: |
            make release
            mv target/aarch64-unknown-linux-musl/release/pingap ./pingap-linux-aarch64
      - name: Upload Assets
        run: |
          ./.github/workflows/upload_asset.sh ./pingap-linux-aarch64 $GITHUB_TOKEN
